### ISSUE TITLE
Incorrect coloring in Python numbers

### ISSUE THREAD

**Issue by cujomalainey** [kenwheeler/brogrammer-theme#10]
When in python and you have a number being assigned to a variable, if it is prefixed with 0 sometimes the color disappears and reverts back to white.
![image](https://cloud.githubusercontent.com/assets/1537150/3845134/7bdfb2a8-1e4f-11e4-9995-d4656c3dc780.png)

**Comment by michaelblyons** [comment]
That's not a bug. Numbers in Python 2 with a leading `0` are octal (base-8). In Python 3, this changed to a leading `0o`. With that in mind, `8` is not a valid octal number because it would be written as `10`.

At any rate, it's more likely to be the Python syntax you're using than the theme.

**Comment by cujomalainey** [comment]
I was not aware that there was a different standard in python 2, I was only aware of the python3 standard. Thanks for the information.
